### ISSUE TITLE
Lead generation and Tracking

### ISSUE THREAD

**Issue by vinay-qfi** [vinay-qfi/leads_be#2]
Build APIs for generating and tracking leads

- [ ] Setup database and db models
- [ ] Set up Lead Mock APIs
- [ ] Lead CRUD APIs
- [ ] List Leads API, Search Leads API
- [ ] Testing & QA
